CREATE TABLE `temporary_MIS` (
  `Date_Time` DATE NOT NULL,
  `Cpu_Count` INT NOT NULL,
  `Cpu_Working_Time` DOUBLE(11,3) NOT NULL,
  `Cpu_idle_Time` DOUBLE(11,3) NOT NULL,
  `cpu_percent` DOUBLE(11,3) NOT NULL,
  `Usage_cpu_count` INT NOT NULL,
  `number_of_software_interrupts_since_boot` DOUBLE(11,3) NOT NULL,
  `number_of_system_calls_since_boot` INT NOT NULL,
  `number_of_interrupts_since_boot` INT NOT NULL,
  `cpu_avg_load_over_1_min` DOUBLE(11,3) NOT NULL,
  `cpu_avg_load_over_5_min` DOUBLE(11,3) NOT NULL,
  `cpu_avg_load_over_15_min` DOUBLE(11,3) NOT NULL,
  `system_total_memory` BIGINT NOT NULL,
  `system_used_memory` BIGINT NOT NULL,
  `system_free_memory` BIGINT NOT NULL,
  `system_active_memory` BIGINT NOT NULL,
  `system_inactive_memory` BIGINT NOT NULL,
  `system_buffers_memory` BIGINT NOT NULL,
  `system_cached_memory` BIGINT NOT NULL,
  `system_shared_memory` BIGINT NOT NULL,
  `system_avalible_memory` BIGINT NOT NULL,
  `disk_total_memory` BIGINT NOT NULL,
  `disk_used_memory` BIGINT NOT NULL,
  `disk_free_memory` BIGINT NOT NULL,
  `disk_read_count` BIGINT NOT NULL,
  `disk_write_count` BIGINT NOT NULL,
  `disk_read_bytes` BIGINT NOT NULL,
  `disk_write_bytes` BIGINT NOT NULL,
  `time_spent_reading_from_disk` BIGINT NOT NULL,
  `time_spent_writing_to_disk` BIGINT NOT NULL,
  `time_spent_doing_actual_Input_Output` BIGINT NOT NULL,
  `number_of_bytes_sent` BIGINT NOT NULL,
  `number_of_bytes_received` BIGINT NOT NULL,
  `number_of_packets_sent` BIGINT NOT NULL,
  `number_of_packets_recived` BIGINT NOT NULL,
  `total_number_of_errors_while_receiving` BIGINT NOT NULL,
  `total_number_of_errors_while_sending` BIGINT NOT NULL,
  `total_number_of_incoming_packets_which_were_dropped` BIGINT NOT NULL,
  `total_number_of_outgoing_packets_which_were_dropped` BIGINT NOT NULL,
  `boot_time` VARCHAR(100) NOT NULL,
  `user_name` VARCHAR(50) NOT NULL,
  `keyboard` INT NOT NULL,
  `mouse` INT NOT NULL,
  `technology` VARCHAR(100) NOT NULL,
  `files_changed` INT NOT NULL,
  PRIMARY KEY (`user_name`)
);

CREATE TABLE `user_engagement_MIS` (
  `id` int NOT NULL AUTO_INCREMENT,
  `candidate_id` int NOT NULL,
  `Date_Time` date NOT NULL,
  `Cpu_Count` int NOT NULL,
  `Cpu_Working_Time` double(11,3) NOT NULL,
  `Cpu_idle_Time` double(11,3) NOT NULL,
  `cpu_percent` double(11,3) NOT NULL,
  `Usage_cpu_count` int NOT NULL,
  `number_of_software_interrupts_since_boot` double(11,3) NOT NULL,
  `number_of_system_calls_since_boot` int NOT NULL,
  `number_of_interrupts_since_boot` int NOT NULL,
  `cpu_avg_load_over_1_min` double(11,3) NOT NULL,
  `cpu_avg_load_over_5_min` double(11,3) NOT NULL,
  `cpu_avg_load_over_15_min` double(11,3) NOT NULL,
  `system_total_memory` bigint NOT NULL,
  `system_used_memory` bigint NOT NULL,
  `system_free_memory` bigint NOT NULL,
  `system_active_memory` bigint NOT NULL,
  `system_inactive_memory` bigint NOT NULL,
  `system_buffers_memory` bigint NOT NULL,
  `system_cached_memory` bigint NOT NULL,
  `system_shared_memory` bigint NOT NULL,
  `system_avalible_memory` bigint NOT NULL,
  `disk_total_memory` bigint NOT NULL,
  `disk_used_memory` bigint NOT NULL,
  `disk_free_memory` bigint NOT NULL,
  `disk_read_count` bigint NOT NULL,
  `disk_write_count` bigint NOT NULL,
  `disk_read_bytes` bigint NOT NULL,
  `disk_write_bytes` bigint NOT NULL,
  `time_spent_reading_from_disk` bigint NOT NULL,
  `time_spent_writing_to_disk` bigint NOT NULL,
  `time_spent_doing_actual_Input_Output` bigint NOT NULL,
  `number_of_bytes_sent` bigint NOT NULL,
  `number_of_bytes_received` bigint NOT NULL,
  `number_of_packets_sent` bigint NOT NULL,
  `number_of_packets_recived` bigint NOT NULL,
  `total_number_of_errors_while_receiving` bigint NOT NULL,
  `total_number_of_errors_while_sending` bigint NOT NULL,
  `total_number_of_incoming_packets_which_were_dropped` bigint NOT NULL,
  `total_number_of_outgoing_packets_which_were_dropped` bigint NOT NULL,
  `boot_time` varchar(100) NOT NULL,
  `keyboard` int NOT NULL,
  `mouse` int NOT NULL,
  `technology` varchar(100) NOT NULL,
  `files_changed` int NOT NULL,
  PRIMARY KEY (`id`),
  KEY `FK_user_engagement_mis_candidate_id` (`candidate_id`),
  CONSTRAINT `FK_user_engagemnt_mis_candidate_id` FOREIGN KEY (`candidate_id`) REFERENCES `Fellowship_Candidate` (`id`)
);

-- Load csv file to table
LOAD DATA LOCAL INFILE '~/Downloads/CpuLogData2019-11-17-new.csv' INTO TABLE temporary_MIS FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n' IGNORE 1 ROWS (Date_Time , Cpu_Count , Cpu_Working_Time , Cpu_idle_Time , cpu_percent , Usage_cpu_count , number_of_software_interrupts_since_boot , number_of_system_calls_since_boot , number_of_interrupts_since_boot , cpu_avg_load_over_1_min, cpu_avg_load_over_5_min  , cpu_avg_load_over_15_min , system_total_memory  , system_used_memory , system_free_memory , system_active_memory , system_inactive_memory , system_buffers_memory, system_cached_memory , system_shared_memory , system_avalible_memory , disk_total_memory , disk_used_memory , disk_free_memory , disk_read_count , disk_write_count , disk_read_bytes , disk_write_bytes , time_spent_reading_from_disk , time_spent_writing_to_disk , time_spent_doing_actual_Input_Output , number_of_bytes_sent , number_of_bytes_received , number_of_packets_sent , number_of_packets_recived , total_number_of_errors_while_receiving , total_number_of_errors_while_sending , total_number_of_incoming_packets_which_were_dropped , total_number_of_outgoing_packets_which_were_dropped , boot_time, user_name , keyboard , mouse , technology , files_changed );

-- insert data from temporary MIS table

INSERT INTO user_engagement_MIS(candidate_id,
Date_Time,
Cpu_Count,
Cpu_Working_Time,
Cpu_idle_Time,
cpu_percent,
Usage_cpu_count,
number_of_software_interrupts_since_boot,
number_of_system_calls_since_boot,
number_of_interrupts_since_boot,
cpu_avg_load_over_1_min,
cpu_avg_load_over_5_min,
cpu_avg_load_over_15_min,
system_total_memory,
system_used_memory,
system_free_memory,
system_active_memory,
system_inactive_memory,
system_buffers_memory,
system_cached_memory,
system_shared_memory,
system_avalible_memory,
disk_total_memory,
disk_used_memory,
disk_free_memory,
disk_read_count,
disk_write_count,
disk_read_bytes,
disk_write_bytes,
time_spent_reading_from_disk,
time_spent_writing_to_disk,
time_spent_doing_actual_Input_Output,
number_of_bytes_sent,
number_of_bytes_received,
number_of_packets_sent,
number_of_packets_recived,
total_number_of_errors_while_receiving,
total_number_of_errors_while_sending,
total_number_of_incoming_packets_which_were_dropped,
total_number_of_outgoing_packets_which_were_dropped,
boot_time,
keyboard,
mouse,
technology,
files_changed)
(select Fellowship_Candidate.id,
temporary_MIS.Date_Time,
temporary_MIS.Cpu_Count,
temporary_MIS.Cpu_Working_Time,
temporary_MIS.Cpu_idle_Time,
temporary_MIS.cpu_percent,
temporary_MIS.Usage_cpu_count,
temporary_MIS.number_of_software_interrupts_since_boot,
temporary_MIS.number_of_system_calls_since_boot,
temporary_MIS.number_of_interrupts_since_boot,
temporary_MIS.cpu_avg_load_over_1_min,
temporary_MIS.cpu_avg_load_over_5_min,
temporary_MIS.cpu_avg_load_over_15_min,
temporary_MIS.system_total_memory,
temporary_MIS.system_used_memory,
temporary_MIS.system_free_memory,
temporary_MIS.system_active_memory,
temporary_MIS.system_inactive_memory,
temporary_MIS.system_buffers_memory,
temporary_MIS.system_cached_memory,
temporary_MIS.system_shared_memory,
temporary_MIS.system_avalible_memory,
temporary_MIS.disk_total_memory,
temporary_MIS.disk_used_memory,
temporary_MIS.disk_free_memory,
temporary_MIS.disk_read_count,
temporary_MIS.disk_write_count,
temporary_MIS.disk_read_bytes,
temporary_MIS.disk_write_bytes,
temporary_MIS.time_spent_reading_from_disk,
temporary_MIS.time_spent_writing_to_disk,
temporary_MIS.time_spent_doing_actual_Input_Output,
temporary_MIS.number_of_bytes_sent,
temporary_MIS.number_of_bytes_received,
temporary_MIS.number_of_packets_sent,
temporary_MIS.number_of_packets_recived,
temporary_MIS.total_number_of_errors_while_receiving,
temporary_MIS.total_number_of_errors_while_sending,
temporary_MIS.total_number_of_incoming_packets_which_were_dropped,
temporary_MIS.total_number_of_outgoing_packets_which_were_dropped,
temporary_MIS.boot_time,
temporary_MIS.keyboard,
temporary_MIS.mouse,
temporary_MIS.technology,
temporary_MIS.files_changed from temporary_MIS
INNER JOIN Fellowship_Candidate
ON Fellowship_Candidate.Email_Id = temporary_MIS.user_name);


SELECT Fellowship_Candidate.id, Fellowship_Candidate.First_Name, Fellowship_Candidate.Last_Name FROM Fellowship_Candidate
INNER JOIN user_engagement_MIS
ON Fellowship_Candidate.id = user_engagement_MIS.candidate_id;

SELECT * FROM Fellowship_Candidate
INNER JOIN user_engagement_MIS
ON Fellowship_Candidate.id = user_engagement_MIS.candidate_id
where date_format(user_engagement_MIS.Date_Time, '%H:%i:%s') > '08:30:00';

SELECT Fellowship_Candidate.id, Fellowship_Candidate.First_Name, Fellowship_Candidate.Last_Name FROM Fellowship_Candidate
INNER JOIN user_engagement_MIS
ON Fellowship_Candidate.id = user_engagement_MIS.candidate_id
where user_engagement_MIS.Date_Time > DATE_ADD("2019-11-17", INTERVAL '08:30' HOUR_MINUTE);


SELECT * FROM Fellowship_Candidate
INNER JOIN user_engagement_MIS
ON Fellowship_Candidate.id = user_engagement_MIS.candidate_id
where date_format(user_engagement_MIS.Date_Time, '%H:%i:%s') < '08:30:00';

explain SELECT Fellowship_Candidate.id, Fellowship_Candidate.First_Name, Fellowship_Candidate.Last_Name FROM Fellowship_Candidate
INNER JOIN user_engagement_MIS
ON Fellowship_Candidate.id = user_engagement_MIS.candidate_id
where user_engagement_MIS.Date_Time < DATE_ADD("2019-11-17", INTERVAL '08:30' HOUR_MINUTE);